// 10 profils QuestionnaireData couvrant la couverture max
// Format : doit correspondre à src/types.ts QuestionnaireData

const isoFromNow = (weeks) => {
  const d = new Date();
  d.setDate(d.getDate() + weeks * 7);
  return d.toISOString().split('T')[0];
};
const today = new Date().toISOString().split('T')[0];

export const PROFILES = [
  // 1 — DÉBUTANT VOLUME 0 + MARATHON 16 sem
  {
    label: 'DEBUTANT_VOL0_MARATHON',
    data: {
      sex: 'Homme',
      goal: 'Course sur route',
      subGoal: 'Marathon',
      level: 'Débutant (0-1 an)',
      frequency: 3,
      preferredDays: ['Mardi', 'Jeudi', 'Dimanche'],
      preferredLongRunDay: 'Dimanche',
      startDate: today,
      raceDate: isoFromNow(16),
      targetTime: 'Finisher',
      age: 32,
      weight: 78,
      height: 178,
      city: 'Lyon',
      recentRaceTimes: {},
      injuries: { hasInjury: false },
      currentWeeklyVolume: 0,
      comments: 'Premier marathon, jamais couru plus de 5km',
      email: 'test1@example.com',
    },
  },

  // 2 — DÉBUTANT IMC>30 + PERTE DE POIDS — reprise après pause
  {
    label: 'DEBUTANT_IMC32_PDP',
    data: {
      sex: 'Femme',
      goal: 'Perte de poids',
      subGoal: '',
      level: 'Débutant (0-1 an)',
      frequency: 3,
      preferredDays: ['Lundi', 'Mercredi', 'Samedi'],
      preferredLongRunDay: 'Samedi',
      startDate: today,
      raceDate: isoFromNow(12),
      targetTime: '',
      age: 38,
      weight: 92,
      height: 168,
      city: 'Marseille',
      recentRaceTimes: {},
      injuries: { hasInjury: false },
      currentWeeklyVolume: 5,
      weightLossSubGoal: 'Reprendre une activité régulière',
      fitnessSubGoal: 'Reprendre après une pause',
      lastActivity: 'Plus de 6 mois',
      comments: 'Veux retrouver la forme en douceur',
      email: 'test2@example.com',
    },
  },

  // 3 — INTERMÉDIAIRE + 10K en 45 min, 10 sem
  {
    label: 'INTER_10K_45MIN',
    data: {
      sex: 'Homme',
      goal: 'Course sur route',
      subGoal: '10 km',
      level: 'Intermédiaire (Régulier)',
      frequency: 4,
      preferredDays: ['Lundi', 'Mercredi', 'Vendredi', 'Dimanche'],
      preferredLongRunDay: 'Dimanche',
      startDate: today,
      raceDate: isoFromNow(10),
      targetTime: '45min',
      age: 35,
      weight: 72,
      height: 180,
      city: 'Paris',
      recentRaceTimes: { distance5km: '22:30' },
      injuries: { hasInjury: false },
      currentWeeklyVolume: 30,
      comments: '',
      email: 'test3@example.com',
    },
  },

  // 4 — INTERMÉDIAIRE + SEMI 1h45, 14 sem
  {
    label: 'INTER_SEMI_1H45',
    data: {
      sex: 'Femme',
      goal: 'Course sur route',
      subGoal: 'Semi-Marathon',
      level: 'Intermédiaire (Régulier)',
      frequency: 4,
      preferredDays: ['Mardi', 'Jeudi', 'Samedi', 'Dimanche'],
      preferredLongRunDay: 'Dimanche',
      startDate: today,
      raceDate: isoFromNow(14),
      targetTime: '1h45',
      age: 33,
      weight: 60,
      height: 168,
      city: 'Bordeaux',
      recentRaceTimes: { distance10km: '48:00' },
      injuries: { hasInjury: false },
      currentWeeklyVolume: 35,
      comments: '',
      email: 'test4@example.com',
    },
  },

  // 5 — CONFIRMÉ + MARATHON CHRONO 3h15 16 sem
  {
    label: 'CONFIRME_MARATHON_3H15',
    data: {
      sex: 'Homme',
      goal: 'Course sur route',
      subGoal: 'Marathon',
      level: 'Confirmé (Compétition)',
      frequency: 5,
      preferredDays: ['Lundi', 'Mardi', 'Jeudi', 'Vendredi', 'Dimanche'],
      preferredLongRunDay: 'Dimanche',
      startDate: today,
      raceDate: isoFromNow(16),
      targetTime: '3h15',
      age: 38,
      weight: 70,
      height: 178,
      city: 'Nantes',
      recentRaceTimes: { distance10km: '40:00', distanceHalfMarathon: '1:28:00' },
      injuries: { hasInjury: false },
      currentWeeklyVolume: 50,
      comments: 'Objectif chrono ferme',
      email: 'test5@example.com',
    },
  },

  // 6 — CONFIRMÉ + TRAIL 45km/2500D+, 16 sem
  {
    label: 'CONFIRME_TRAIL_45KM_2500D',
    data: {
      sex: 'Homme',
      goal: 'Trail',
      subGoal: '',
      trailDetails: { distance: 45, elevation: 2500 },
      level: 'Confirmé (Compétition)',
      frequency: 5,
      preferredDays: ['Mardi', 'Mercredi', 'Vendredi', 'Samedi', 'Dimanche'],
      preferredLongRunDay: 'Dimanche',
      startDate: today,
      raceDate: isoFromNow(16),
      targetTime: 'Finisher',
      age: 40,
      weight: 73,
      height: 180,
      city: 'Grenoble',
      recentRaceTimes: { distanceHalfMarathon: '1:32:00' },
      injuries: { hasInjury: false },
      currentWeeklyVolume: 45,
      currentWeeklyElevation: 800,
      comments: '',
      email: 'test6@example.com',
    },
  },

  // 7 — EXPERT + ULTRA 100km/5000D+, 24 sem, chrono
  {
    label: 'EXPERT_ULTRA_100KM_5000D',
    data: {
      sex: 'Homme',
      goal: 'Trail',
      subGoal: '',
      trailDetails: { distance: 100, elevation: 5000 },
      level: 'Expert (Performance)',
      frequency: 6,
      preferredDays: ['Lundi', 'Mardi', 'Mercredi', 'Vendredi', 'Samedi', 'Dimanche'],
      preferredLongRunDay: 'Samedi',
      startDate: today,
      raceDate: isoFromNow(24),
      targetTime: '15h00',
      age: 42,
      weight: 68,
      height: 178,
      city: 'Chamonix',
      recentRaceTimes: { distanceMarathon: '3:05:00' },
      injuries: { hasInjury: false },
      currentWeeklyVolume: 60,
      currentWeeklyElevation: 1800,
      comments: '',
      email: 'test7@example.com',
    },
  },

  // 8 — EXPERT + UTMB 170km/10000D+, 30 sem
  {
    label: 'EXPERT_UTMB_170KM_10000D',
    data: {
      sex: 'Homme',
      goal: 'Trail',
      subGoal: '',
      trailDetails: { distance: 170, elevation: 10000 },
      level: 'Expert (Performance)',
      frequency: 6,
      preferredDays: ['Lundi', 'Mardi', 'Mercredi', 'Vendredi', 'Samedi', 'Dimanche'],
      preferredLongRunDay: 'Samedi',
      startDate: today,
      raceDate: isoFromNow(30),
      targetTime: 'Finisher',
      age: 45,
      weight: 70,
      height: 180,
      city: 'Chamonix',
      recentRaceTimes: { distanceMarathon: '3:10:00' },
      injuries: { hasInjury: false },
      currentWeeklyVolume: 70,
      currentWeeklyElevation: 2500,
      comments: '',
      email: 'test8@example.com',
    },
  },

  // 9 — INTERMÉDIAIRE + HYROX freq 4, 10 sem
  {
    label: 'INTER_HYROX',
    data: {
      sex: 'Femme',
      goal: 'Hyrox',
      subGoal: '',
      level: 'Intermédiaire (Régulier)',
      frequency: 4,
      preferredDays: ['Lundi', 'Mercredi', 'Vendredi', 'Dimanche'],
      preferredLongRunDay: 'Dimanche',
      startDate: today,
      raceDate: isoFromNow(10),
      targetTime: '',
      age: 30,
      weight: 62,
      height: 168,
      city: 'Toulouse',
      recentRaceTimes: { distance10km: '52:00' },
      injuries: { hasInjury: false },
      currentWeeklyVolume: 25,
      hyroxPreviousTime: '1h30',
      comments: '',
      email: 'test9@example.com',
    },
  },

  // 10 — DÉBUTANT LOW VMA + 5K, 8 sem
  {
    label: 'DEBUTANT_LOWVMA_5K',
    data: {
      sex: 'Femme',
      goal: 'Course sur route',
      subGoal: '5 km',
      level: 'Débutant (0-1 an)',
      frequency: 3,
      preferredDays: ['Mardi', 'Jeudi', 'Samedi'],
      preferredLongRunDay: 'Samedi',
      startDate: today,
      raceDate: isoFromNow(8),
      targetTime: '',
      age: 28,
      weight: 58,
      height: 165,
      city: 'Rennes',
      recentRaceTimes: {},
      injuries: { hasInjury: false },
      currentWeeklyVolume: 8,
      comments: 'Première course 5km',
      email: 'test10@example.com',
    },
  },
];
